# four node (one control plane + three workers) cluster config for k8s e2e test in github workflow!
# for the local registry config see https://kind.sigs.k8s.io/docs/user/local-registry/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
      endpoint = ["http://kind-registry:5000"]